version: '3'

services:
  openvpn:
    image: ichikawayukko/openvpn_ipv6
    restart: always
    volumes:
      - ./volume/:/etc/openvpn/:z
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "1194:1194/udp"
    container_name: openvpn
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv6.conf.all.forwarding: 1
    devices:
      - /dev/net/tun

volumes:
  openvpn:
    driver: local

